version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - "5000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/myportfolio
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
     - ./flask.sqlite:/myportfolio/flask.sqlite
